version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: mkdir test-reports
      - run: sudo pip install selenium
      - run: sudo pip install unittest2
      - run: 
          command: python TestCase.py
