version: 2
jobs:
  build:
    docker:
      - image: circleci/python:jessie-node-browsers
    steps:
      - checkout
      - run: curl -o index.html https://raw.githubusercontent.com/AaronFox-4/CircleCI-Challenge/master/index.html 
      - run: curl -o styles.css https://raw.githubusercontent.com/AaronFox-4/CircleCI-Challenge/master/styles.css
      - run: mkdir test-reports
      - run: sudo pip install selenium
      - run: sudo pip install requests
      - run: 
          command: python TestCase.py
